### ISSUE TITLE
HELP !!! IPAdapterUnifiedLoader IPAdapter model not found

### ISSUE THREAD

**Issue by FaranYousufi** [cubiq/ComfyUI_IPAdapter_plus#844]
<img width="3800" height="1862" alt="Image" src="https://github.com/user-attachments/assets/18f45f2f-9ca9-486f-992a-600825d1e36d" />

<img width="1620" height="623" alt="Image" src="https://github.com/user-attachments/assets/a9ce02ad-7ddd-4223-afa8-920383dd42bd" />

<img width="1743" height="906" alt="Image" src="https://github.com/user-attachments/assets/77f04649-b2a0-4a4c-9958-5eac819e8c01" />

**Comment by FaranYousufi** [comment]
<img width="2559" height="1369" alt="Image" src="https://github.com/user-attachments/assets/e4935261-f4f1-44ae-801d-70ea2314ab28" />

**Comment by rcstone0** [comment]
me too

**Comment by suninjang1020-creator** [comment]
저도요 왜이래요 이거

**Comment by ricmetal** [comment]
same. using ip-adapter-plus_sdxl_vit-h.safetensors
but i have the model in ComfyUI/Models/IPAdapter folder

**Comment by FaranYousufi** [comment]
It solved by placing models in the right folder 
follow github instructions is given

**Comment by hsysss-a11y** [comment]
Do you guys enter the new IPAdapter folder location in the "extra_model_paths.yaml" file. after you had relocated the folder path? 

I am trying this method now since I downloaded all the models file and it still show the "Model not found"error again.

<img width="1069" height="371" alt="Image" src="https://github.com/user-attachments/assets/bc8446aa-eb6c-4a54-82c2-8324055a7eff" />

**Comment by hsysss-a11y** [comment]
> Do you guys enter the new IPAdapter folder location in the "extra_model_paths.yaml" file. after you had relocated the folder path?
> 
> I am trying this method now since I downloaded all the models file and it still show the "Model not found"error again.
> <img alt="Image" width="1069" height="371" src="https://private-user-images.githubusercontent.com/148851839/497433146-bc8446aa-eb6c-4a54-82c2-8324055a7eff.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk1NzYxNjcsIm5iZiI6MTc1OTU3NTg2NywicGF0aCI6Ii8xNDg4NTE4MzkvNDk3NDMzMTQ2LWJjODQ0NmFhLWViNmMtNGE1NC04MmMyLTgzMjQwNTVhN2VmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwNFQxMTA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWM4NWZmNWVmODU5YWNhMjM3ZWE5N2EzNDE2OTdhMDgzNjhkZmRhY2Y5MGFmNDczODVkZGY5ZjBmMWI2MDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N4Im-rfhpR9D99iHbQAPVXtMViNvi4tGAY8XtCPFO_8">

It works for me, remember to type the path correctly

<img width="353" height="460" alt="Image" src="https://github.com/user-attachments/assets/bdac7c69-093c-486c-9da8-fa838fc9e27f" />

**Comment by modipiyush** [comment]
I tried everything but still not working, reinstall this custom node and dependency, also download models related to ipadapter,

**Comment by drocologue** [comment]
> I tried everything but still not working, reinstall this custom node and dependency, also download models related to ipadapter,

did u find a fix?

**Comment by hsysss-a11y** [comment]
> I tried everything but still not working, reinstall this custom node and dependency, also download models related to ipadapter,

For your information, I used this version and the yaml file renames as "extra_model_config.yaml"

![Image](https://github.com/user-attachments/assets/c8566551-3973-47a2-8701-f23b74b5ea5e)

by the way, I am not using portable version of ComfyUI.

**Comment by modipiyush** [comment]
Yes 
Download all depandency like 
You can check  Ipadapter Model page
It's two types of models 
Ipadapter SD15 models or IPadapter faceid models 
For unified loader you should download ipadapter SD15 models and clip vision models
It works for me 

> > I tried everything but still not working, reinstall this custom node and dependency, also download models related to ipadapter,
> 
> did u find a fix?

**Comment by modipiyush** [comment]
Download all depandency like
You can check Ipadapter Model page
It's two types of models
Ipadapter SD15 models or IPadapter faceid models
For unified loader you should download ipadapter SD15 models and clip vision models
It works for me
I'm using in linux and windows portable also 

> > I tried everything but still not working, reinstall this custom node and dependency, also download models related to ipadapter,
> 
> For your information, I used this version and the yaml file renames as "extra_model_config.yaml"
> 
> ![Image](https://github.com/user-attachments/assets/c8566551-3973-47a2-8701-f23b74b5ea5e)
> 
> by the way, I am not using portable version of ComfyUI.

**Comment by ghost** [comment]
I got it working with ipadapter_style_composition.json workflow
-create extra_model_paths.yaml file in comfyui root directory, and add the single line "ipadapter:models/ipadapter/"10000
-download the 3 clip_vision models into your clip_vision folder, named as specified
-downloaded all the ipadapter files from the top list (except the ones that required bigG clip, and the last deprecated one)
-downloaded all the ipadapter .bin files (except the 2 deprecated ones)

**Comment by MichT368** [comment]
Go to
/your/patht/to/ComfyUI/extra_model_paths.yaml

Open the file in an editor and add:

comfyui:
  ipadapter: |-
    /your/path/To/ComfyUI/models/ipadapter/
